name: test-github-action-schedule
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '2 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Running
        run: |
          echo "Running!"
